### ISSUE TITLE
Fails to get cookies on iOS

### ISSUE THREAD

**Issue by iverc** [fryette/webview_cookie_manager#20] opened 2020-10-28 12:28 UTC
It works as expected on Android, but on iOS (11.0+) it returns empty array. Flutter code is equivalent for both platforms, so I suppose there is an issue when interacting with native iOS cookie manager.

**Comment by fryette** [comment] 2020-10-28 12:51
Hi! I would like to help but I need some input from you.

1. Could you please share MRE(Minimum reproducible example)?
2. After setting cookies could you please add ```await Future.delay(Duration(seconds:3))```, and then get cookies again. Any result appears?

**Comment by iverc** [comment] 2020-10-30 18:56
HI @fryette, thanks for quick response.
1. Basically, I open a website in the webview (e.g. youtube.com). Then I use the cookie manager to get cookies from that website like in example `final gotCookies = await cookieManager.getCookies('https://youtube.com');`
When I do that on Android, everything works as expected and I get an array of cookies. Doing the same on iOS device returns an empty array.
2. I do not set any cookies manually, so not sure if adding a delay would help.

Thank you!

**Comment by JosephNK** [comment] 2020-11-09 02:31
It would be nice to have a function like getAllCookies.
In hasCookies, something says there is a cookie...
I don't know what cookies are in flutter.

**Comment by fryette** [comment] 2020-11-09 06:09
@JosephNK do you know a native way to implement it?

**Comment by JosephNK** [comment] 2020-11-09 06:47
@fryette  I checked the ios native source.
When you call getCookies(null), you get all cookies. :)

**Comment by JosephNK** [comment] 2020-11-09 06:52
Strangely, when calling getCookies(null) in ios, there are times when cookie cannot be fetched.

**Comment by JosephNK** [comment] 2020-11-09 06:55
Please consider importing as HTTPCookieStorage.shared.cookies, not WKWebsiteDataStore.default().httpCookieStore.

**Comment by fryette** [comment] 2020-11-09 07:04
@JosephNK but for android you cannot, right?

**Comment by JosephNK** [comment] 2020-11-09 08:37
@fryette PR[#21] please check.

**Comment by fryette** [comment] 2020-11-09 09:13
@JosephNK will check it today or tomorrow morning and will provide a new version if everything is OK

**Comment by i-Senku** [comment] 2020-11-09 14:03
i have same issue. I can't get cookie from ios.

**Comment by seukaiwokeo** [comment] 2020-11-09 17:04
Same problem for me.

**Comment by fryette** [comment] 2020-11-10 06:18
@seukaiwokeo @i-Senku could you please grab PR(https://github.com/fryette/webview_cookie_manager/pull/21) and check it?

It can be done with:
```
  webview_cookie_manager:
    git:
      url: https://github.com/JosephNK/webview_cookie_manager.git
```

**Comment by i-Senku** [comment] 2020-11-10 08:45
@fryette  It's doesn't work. getCookies functions returned empty Cookie List.

**Comment by JosephNK** [comment] 2020-11-10 08:58
@i-Senku 
When you set getCookies(null), in the case of Android, an empty list is correct. The reason is that Android can't get all the lists. And in the case of iOS, a list should appear. Did you test on Android? Did you do it with iOS?

**Comment by i-Senku** [comment] 2020-11-10 09:32
@JosephNK yep i tested on IOS with offical webview package. But it return empty list. Did you tested on IOS ? Because it's doesnt work on my project :(

**Comment by JosephNK** [comment] 2020-11-10 09:39
@i-Senku yeb i tested on iOS. It works in my project with a modified version.

After modifying as below in the pubspec.yaml file
```
webview_cookie_manager:
    git:
      url: https://github.com/JosephNK/webview_cookie_manager.git
      ref: 65979e2064fcdf5d98c0b2159ca5f4873f0259d8
```
After executing the command as below
```
$ flutter clean
$ flutter pub get
```
Try build
```
Run build iOS
```

**Comment by i-Senku** [comment] 2020-11-10 09:54
@JosephNK  
Webview Scene. I added breakpoint to getCookies function and it looks empty. Where am i doing wrong ? 

```
    return SafeArea(
        child: Scaffold(
      body: WebView(
        initialUrl: "https://www.instagram.com/accounts/login/",
        javascriptMode: JavascriptMode.unrestricted,
        onPageFinished: (url) async {
          var cookies = await cookieManager.getCookies(url);
          cookies.forEach((element) {
            print(element.name);
          });
        },
      ),
    ));
```

pubspec file.

<img width="711" alt="Ekran Resmi 2020-11-10 12 49 39" src="https://user-images.githubusercontent.com/54575884/98657892-7230f180-2353-11eb-858d-1988ae39ae55.png">

**Comment by JosephNK** [comment] 2020-11-10 09:58
@i-Senku 

getCookies(url) to getCookies(null)

can u try?

**Comment by JosephNK** [comment] 2020-11-10 10:06
@i-Senku 

When flutter passes the url value as a parameter, if you check the iOS native code, there may be cases where the host of the url value does not match when searching for the cookie value in the cookie storage.  For example, in case of a wildcard, a case of mismatch occurs.

**Comment by i-Senku** [comment] 2020-11-10 10:10
idk why i tried this code ( getCookies(null) ). What should I do now? Do you have a solution? I want to receive cookies from Instagram

<img width="1364" alt="Ekran Resmi 2020-11-10 13 08 12" src="https://user-images.githubusercontent.com/54575884/98660070-ee2c3900-2355-11eb-9df7-46ff017d0700.png">

**Comment by JosephNK** [comment] 2020-11-10 10:26
@i-Senku @fryette 
Oops... I think the error is... I think you need to check the Future<List<Cookie>> getCookies(String currentUrl) function.

**Comment by JosephNK** [comment] 2020-11-12 11:45
@i-Senku @fryette 
Fixed Invalid Char issue when creating a cookie for darts. https://github.com/fryette/webview_cookie_manager/pull/21/commits/70e8e0cbc7cfacfbb7abb7917e70a78a0744681b

**Comment by i-Senku** [comment] 2020-11-12 11:53
ı fixed get cookies problem in ios. I founded problem in getCookies function. This code working 

```
func getCookies(url : String,result: @escaping FlutterResult){
    var cookieList = [[String: Any]]()
    let cookieStore = WKWebsiteDataStore.default().httpCookieStore
    cookieStore.getAllCookies { (cookies) in
        for cookie in cookies {
            cookieList.append(cookieToDictionary(cookie: cookie))
        }
        result(cookieList)
    }
}
```

**Comment by fryette** [comment] 2020-11-12 13:45
@JosephNK maybe we also can include @i-Senku changes to PR?
Or you fix it as well?

**Comment by JosephNK** [comment] 2020-11-12 14:07
@fryette I don't know what kind of code he solved. I already PR the invalied char issue.

**Comment by JosephNK** [comment] 2020-11-12 14:12
@fryette u check out the PR code. or try testing.

**Comment by fryette** [comment] 2020-11-16 07:19
@JosephNK give me a few hours

**Comment by fryette** [comment] 2020-11-16 07:57
@JosephNK merged and 1.0.4 version provided.
Thx for your contribution!
If anyone has problems with the new version, feel free to reopen an issue or create a new one

**Closed by fryette** 2020-11-16 07:57 UTC

**Comment by iverc** [comment] 2021-01-20 06:31
@fryette Might be a bit late, tried to raise PR with a fix right away but did not have permission for it. 🤣 
In my particular case, the problem with was the part of logic that did URL check. it was too strict, so if you were on a website with a prefix (e.g. m.website.com), the `.contains()` check for URL match failed and no cookies were returned. The fix was about doing a mirrored check to account for website prefixes. Hope it could be helpful

**Comment by iverc** [comment] 2021-01-20 06:54
@fryette Actually It looks like the problem is still there (unless you set URL to`null`). I can't add a branch or a PR with the fix, could you please allow it?

**Comment by fryette** [comment] 2021-01-20 15:34
@iverc Feel free to fork repo and then you can create a PR with fix

**Comment by iverc** [comment] 2021-01-21 06:52
@fryette https://github.com/fryette/webview_cookie_manager/pull/29

**Comment by fryette** [comment] 2021-01-24 14:46
@iverc new version availbale (1.0.6)
